#!/bin/bash

#
# Check for disk capacity and remove snapshots if capacity is above threshold.
#
VERSION="0.1.0"

ZFS=/sbin/zfs

LOGTAG=$(basename $0)

TESTRUN=0
VOLUME="$(${ZFS} list -Ho name | head -1)"
CAPLIMIT=90

CURRENT_CAPACITY=$(df -P  | grep ${VOLUME} | awk '{ print $5}' | sed 's/%//g')
REMOVED_SNAPSHOTS=0

function print_version(){
	echo ${0##*/} v${VERSION} by Toni Magni
}

function print_help(){
            cat << EOF
${0##*/} v${VERSION} by Toni Magni

Syntax:
${0##*/} [options]

OPTIONS:
	--capacity X	= In percentage, disk capacity threshold (default ${CAPLIMIT}%)
	--volume VOL	= The name of the ZFS dataset volume (default ${VOLUME})
	--version	= Print version and exit
	--help		= Print help and exit
EOF
}

case "$1" in
        '--capacity')
                CAPLIMIT="$2"
                shift 2
                ;;
        '--volume')
                VOLUME="$2"
                shift 2
                ;;
        '--help')
		print_help
                exit 0
                ;;
        '--version')
		print_version
                exit 0
                ;;

esac


while [ ${CURRENT_CAPACITY} -ge ${CAPLIMIT} ]; do
    if [ $(${ZFS} list -t snapshot -o name | grep ${VOLUME} | wc -l) -lt 1 ]; then
        LOGMESSAGE="Disk space is low, but no snapshots found. Can't free up any space."
        logger -t${LOGTAG} ${LOGMESSAGE}
        echo ${LOGMESSAGE} > /dev/stderr
        exit
    fi
    OLDEST_SNAPSHOT=$(${ZFS} list -t snapshot -o name -s creation | grep ${VOLUME} | head -1)
    logger -t${LOGTAG}  "Disk capacity at ${CURRENT_CAPACITY}%. Limit is ${CAPLIMIT}%. Destroying [${OLDEST_SNAPSHOT}]"
    DESTROY="${ZFS} destroy -v ${OLDEST_SNAPSHOT}"
    if [ ${TESTRUN} -eq 1 ]; then
        echo ${DESTROY}
    else
        eval ${DESTROY}
    fi
    ((REMOVED_SNAPSHOTS++))
    sleep 10 # Allow time for FS to write and df to report correctly.
    CURRENT_CAPACITY=$(df -P  | grep ${VOLUME} | awk '{ print $5}' | sed 's/%//g')
    logger -t${LOGTAG}  "Disk capacity now at ${CURRENT_CAPACITY}%."
done

if [ ${REMOVED_SNAPSHOTS} -ne 0 ]; then
    logger -t${LOGTAG}  "${REMOVED_SNAPSHOTS} snapshots removed."
else
    logger -t${LOGTAG}  "Current capacity is only at ${CURRENT_CAPACITY}%. Nothing to be done."
fi
